'use client';

import { OrderTimingAnalytics } from '@/components/admin/OrderTimingAnalytics';

export default function OrderTimingPage() {
    const csvData = `"CURA Order Timing Analytics Report"
"Generated","${new Date().toLocaleString()}"
"Generated By","CURA Administrative Control Panel"
"Report Type","CURA Order Timing Analytics"
"SUMMARY"
"Metric","Value","Description"
"Peak Hour","18:00","240 orders placed"
"Peak Day","Saturday","2200 orders placed"
"Peak Month","June","18500 orders placed"
"Total Orders (6 months)","103200","Sum of all monthly orders"
"Total Revenue (6 months)","EGP 3006000","Sum of all monthly revenue"
"Average Monthly Orders","17200","Average orders per month"
"Average Monthly Revenue","EGP 501000","Average revenue per month"
"HOURLY DISTRIBUTION"
"Hour","Orders","Percentage"
"08:00",45,"2.3%"
"09:00",120,"6.1%"
"10:00",150,"7.6%"
"11:00",90,"4.6%"
"12:00",65,"3.3%"
"13:00",125,"6.4%"
"14:00",180,"9.2%"
"15:00",200,"10.2%"
"16:00",220,"11.2%"
"17:00",240,"12.2%"
"18:00",180,"9.2%"
"19:00",160,"8.2%"
"20:00",140,"7.1%"
"21:00",95,"4.8%"
"22:00",45,"2.3%"
"DAILY DISTRIBUTION"
"Day","Orders","Percentage"
"Monday",1200,"11.6%"
"Tuesday",1450,"14.0%"
"Wednesday",1350,"13.1%"
"Thursday",1600,"15.5%"
"Friday",1850,"17.9%"
"Saturday",2200,"21.3%"
"Sunday",1900,"18.4%"
"MONTHLY TRENDS"
"Month","Orders","Revenue (EGP)","Average Order Value (EGP)"
"January",15200,456000,30
"February",14800,444000,30
"March",16500,495000,30
"April",17200,516000,30
"May",18000,540000,30
"June",18500,555000,30"`;

    const excelData = `\uFEFF"CURA Order Timing Analytics Report"
"Generated","${new Date().toLocaleString()}"
"Generated By","CURA Administrative Control Panel"
"Report Type","CURA Order Timing Analytics"
"SUMMARY"
"Metric","Value","Description"
"Peak Hour","18:00","240 orders placed"
"Peak Day","Saturday","2200 orders placed"
"Peak Month","June","18500 orders placed"
"Total Orders (6 months)","103200","Sum of all monthly orders"
"Total Revenue (6 months)","EGP 3,006,000","Sum of all monthly revenue"
"Average Monthly Orders","17200","Average orders per month"
"Average Monthly Revenue","EGP 501,000","Average revenue per month"
"HOURLY DISTRIBUTION"
"Hour","Orders","Percentage of Daily Total"
"08:00",45,"2.3%"
"09:00",120,"6.1%"
"10:00",150,"7.6%"
"11:00",90,"4.6%"
"12:00",65,"3.3%"
"13:00",125,"6.4%"
"14:00",180,"9.2%"
"15:00",200,"10.2%"
"16:00",220,"11.2%"
"17:00",240,"12.2%"
"18:00",180,"9.2%"
"19:00",160,"8.2%"
"20:00",140,"7.1%"
"21:00",95,"4.8%"
"22:00",45,"2.3%"
"DAILY DISTRIBUTION"
"Day","Orders","Percentage of Weekly Total"
"Monday",1200,"11.6%"
"Tuesday",1450,"14.0%"
"Wednesday",1350,"13.1%"
"Thursday",1600,"15.5%"
"Friday",1850,"17.9%"
"Saturday",2200,"21.3%"
"Sunday",1900,"18.4%"
"MONTHLY TRENDS"
"Month","Orders","Revenue (EGP)","Average Order Value (EGP)"
"January",15200,456000,30
"February",14800,444000,30
"March",16500,495000,30
"April",17200,516000,30
"May",18000,540000,30
"June",18500,555000,30
"ANALYSIS INSIGHTS"
"Insight","Value"
"Peak Hour Performance","18:00 shows highest activity with 240 orders"
"Weekend Effect","Saturday is the busiest day with 2200 orders"
"Seasonal Trend","June shows peak monthly performance"
"Revenue Growth","Consistent 30 EGP average order value"
"Daily Pattern","Evening hours (15:00-19:00) show highest activity"
"Weekly Pattern","Weekend days show 40% higher order volume"`;

    const handleExportCSV = () => {
        const timestamp = new Date().toISOString().split('T')[0];
        const blob = new Blob([csvData], { type: 'text/csv;charset=utf-8;' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `cura-order-timing-analytics-${timestamp}.csv`;
        a.click();
        window.URL.revokeObjectURL(url);
    };

    const handleExportExcel = () => {
        const timestamp = new Date().toISOString().split('T')[0];
        const blob = new Blob([excelData], { type: 'application/vnd.ms-excel;charset=utf-8;' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `cura-order-timing-analytics-${timestamp}.xls`;
        a.click();
        window.URL.revokeObjectURL(url);
    };

    return (
        <div className="min-h-screen bg-gray-50 p-6" data-oid=":m6xenz">
            <div className="max-w-7xl mx-auto" data-oid="omxq4hz">
                <div className="mb-6" data-oid="ft-yjd-">
                    <h1 className="text-3xl font-bold text-gray-900" data-oid=":pa:xk0">
                        Order Timing Analytics
                    </h1>
                    <p className="text-gray-600" data-oid="65gzgkq">
                        Understanding when customers place their orders
                    </p>
                </div>

                <OrderTimingAnalytics
                    onExportCSV={handleExportCSV}
                    onExportExcel={handleExportExcel}
                    data-oid="3l.8xr2"
                />
            </div>
        </div>
    );
}